### ISSUE TITLE
Timeline Event filter buttons are not working.

### ISSUE THREAD

**Issue by razat249** [razat249/github-view#3]
The filter buttons for filtering events like commits, push, gist, fork, issue, comments etc. are not working.
> Initially we only need 4 filters given below.
- [x] Push/Commits
- [x] Comments
- [x] Create
- [x] Forks
- [x] Gist
- [x] Issues

**Comment by htwibowo** [comment]
Hello there, I have made a PR for this issue. Thanks for a great repository, btw. It's going to be awesome!

**Comment by razat249** [comment]
Thanks, @htwibowo. Sure this will going to be awesome. :smile: 
Thanks for your precious, pull request.
