### ISSUE TITLE
Error when starting development server

### ISSUE THREAD

**Issue by erdivartanovich** [razat249/github-view#5]
Failed to compile when run npm start.
Caused by it cannot resolve module redux-logger. Adding this  module dependency explicitly in package.json should resolve the problem

![image](https://cloud.githubusercontent.com/assets/13470318/24579692/4e966d02-1724-11e7-910b-feca789161fc.png)

### Step to reproduce
- clone the repository from https://github.com/razat249/github-view
- run ``` npm install ```
- run ``` npm start ```

**Comment by razat249** [comment]
Hello, @erdivartanovich Thanks for opening this issue. Is it possible for you to make a pull request solving this issue? I think adding dependency to `package.json` will work for us or run `npm i redux-logger -S`

Thanks

**Comment by razat249** [comment]
Thanks, @erdivartanovich for your contribution. :smile: 

Looking forward to more precious contributions from your side.
